name: Java CI

on:
  push:
    branches: [ "sprint_9-solution-http-api" ]  # Триггер для вашей ветки
  pull_request:
    branches: [ "sprint_9-solution-http-api" ]  # И для PR в эту ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test